### ISSUE TITLE
Can't use on this version of macOS

### ISSUE THREAD

**Issue by AntoineFromentin** [esetnik/Aerial#7] opened 2018-05-10 14:55 UTC
My version is 10.13.4

Thanks for the work though. Looking forward to have that 4k feature.

Best

![screen shot 2018-05-10 at 15 54 50](https://user-images.githubusercontent.com/25662572/39876202-7ccd021a-546a-11e8-8b4f-6e1989d0c196.png)

**Comment by esetnik** [comment] 2018-05-10 16:47
Hi @Frockme did you download the compiled binary from the [releases page](https://github.com/esetnik/Aerial/releases/tag/v1.3) or did you compile it yourself? This is most likely a duplicate of https://github.com/esetnik/Aerial/issues/1. I am using Aerial v1.3 on 10.13.4 (17E202) without issues.

**Comment by AntoineFromentin** [comment] 2018-05-10 16:48
Hey man, I've just downloaded the zip file and installed it. I'm not very familiar with GitHub to be honest. :)

**Comment by esetnik** [comment] 2018-05-10 16:53
That's no problem, I can help you through this. Most likely you just need to quit system preferences and reopen it as mentioned [in this ticket comment](https://github.com/esetnik/Aerial/issues/1#issuecomment-346955919)

**Comment by imjustmaxwell** [comment] 2018-06-05 20:20
@esetnik Hello, I am also receiving this issue after updating to MacOS 10.14, unfortunately, neither this or the original version work. Hoping for someone to create a fork with a working version on 10.14.

**Comment by esetnik** [comment] 2018-06-05 20:25
@imjustmaxwell Are you talking about macOS 10.14 beta 1? This just came out yesterday. The most likely guess is that there's either a bug in the beta with regards to third-party screensavers or alternatively that 10.14 only supports screensavers compiled on a newer version of swift. If you'd like to investigate further you can compile this project on the latest Xcode and see if that fixes the issue.

**Comment by imjustmaxwell** [comment] 2018-06-05 20:29
Yes, that's what I'm talking about. I don't know much about using xcode, so I will wait for it to be fixed, but I just wanted to point it out as the whole point of being on beta software is giving feedback on how the OS, and the apps are working. Thank you for your hard work, can't wait to see a 4K version of these screensavers on Mojave!

**Comment by esetnik** [comment] 2018-06-05 20:34
@imjustmaxwell Apple releases developer betas specifically for software developers who must develop against upcoming versions of macOS. If you aren't actively developing software which requires 10.14 and only looking to test it out and give feedback it might be better to wait until 10.14 public beta 1 is released to the general public. You're free to do what you want, but the first 2-3 developer betas of a new macOS are usually really rough and aren't suitable for day-to-day use without a big drop in productivity. I haven't gotten around to testing Aerial on 10.14 yet, but I'll leave this ticket open in case anyone else figures it out before I do.

**Comment by Lucasfranz123321** [comment] 2018-06-06 18:08
Actually I have another Mac which I updated on Mojave and there it works perfectly (MacBook Pro mid 2014)

I guess it may not be problem with the Screensaver itself.

**Comment by esetnik** [comment] 2018-06-06 18:40
@imjustmaxwell did you already review the solution in #1 (namely https://github.com/esetnik/Aerial/issues/1#issuecomment-346955919) to be sure you aren't facing the same issue?

**Comment by kathampy** [comment] 2018-06-13 10:57
The screensaver itself works on 10.14 Beta 1 but the settings page does not.

**Closed as completed** 2018-09-20 14:59 UTC
Labels: help wanted
